version: "3"
services:
  orgapunkt-frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
    ports:
      - 7891:80
  orgapunkt-api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 7892:2342
